<a href="https://colab.research.google.com/github/bondaleksey/in-few-words-about/blob/main/user-item-svd/user_item_SVD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [34]:
import numpy as np
float_formatter = "{:.2f}".format
np.set_printoptions(formatter={'float_kind':float_formatter})

## Пример 1 Квадратная матрица с доминирующим товаром у одного из пользователей

Создадим квадратную матрицу пользователя и товаров

In [35]:
a = np.array([[9, 0, 0], [0, 1, 3], [0, 6, 1]])
print(a)

[[9 0 0]
 [0 1 3]
 [0 6 1]]


Вычислим SVD для этой матрицы

In [36]:
u, s, vh = np.linalg.svd(a, full_matrices=True)
sd = np.multiply(s,np.eye(*a.shape))
print(f"u = \n{u},\nsd = \n{sd},\nvh = \n{vh}")

u = 
[[1.00 0.00 0.00]
 [0.00 -0.29 -0.96]
 [0.00 -0.96 0.29]],
sd = 
[[9.00 0.00 0.00]
 [0.00 6.30 0.00]
 [0.00 0.00 2.70]],
vh = 
[[1.00 0.00 0.00]
 [-0.00 -0.96 -0.29]
 [-0.00 0.29 -0.96]]


Попробуем посмотреть на перемножение U\*S и S\*V 

In [37]:
print(f"u*s = \n{u.dot(sd)}")
print(f"s*vh = \n{sd.dot(vh)}")

u*s = 
[[9.00 0.00 0.00]
 [0.00 -1.83 -2.58]
 [0.00 -6.03 0.78]]
s*vh = 
[[9.00 0.00 0.00]
 [0.00 -6.03 -1.83]
 [0.00 0.78 -2.58]]


## Пример 2 Прямоугольная матрица покупок

In [41]:
a = np.array([[2, 0], [0, 6], [1, 2]])
print(f"Matrix is \n{a}")
u, s, vh = np.linalg.svd(a, full_matrices=True)
sd = np.multiply(s,np.eye(*a.shape))
print(f"u = \n{u},\nsd = \n{sd},\nvh = \n{vh}")
print(f"u*s = \n{u.dot(sd)}")
print(f"s*vh = \n{sd.dot(vh)}")

Matrix is 
[[2 0]
 [0 6]
 [1 2]]
u = 
[[-0.02 0.90 -0.43]
 [-0.95 -0.15 -0.29]
 [-0.32 0.40 0.86]],
sd = 
[[6.33 0.00]
 [0.00 2.21]
 [0.00 0.00]],
vh = 
[[-0.06 -1.00]
 [1.00 -0.06]]
u*s = 
[[-0.11 2.00]
 [-5.99 -0.34]
 [-2.05 0.88]]
s*vh = 
[[-0.36 -6.32]
 [2.21 -0.13]
 [0.00 0.00]]


## Пример 3 Квадратная вырожденная матрица покупок

In [38]:
a = np.array([[1, 0, 0], [1, 0  , 2], [2, 0, 1]])
print(f"Matrix is \n{a}")
u, s, vh = np.linalg.svd(a, full_matrices=True)
sd = np.multiply(s,np.eye(*a.shape))
print(f"u = \n{u},\nsd = \n{sd},\nvh = \n{vh}")
print(f"u*s = \n{u.dot(sd)}")
print(f"s*vh = \n{sd.dot(vh)}")

Matrix is 
[[1 0 0]
 [1 0 2]
 [2 0 1]]
u = 
[[-0.24 0.55 -0.80]
 [-0.67 -0.69 -0.27]
 [-0.70 0.47 0.53]],
sd = 
[[3.09 0.00 0.00]
 [0.00 1.21 0.00]
 [0.00 0.00 0.00]],
vh = 
[[-0.75 0.00 -0.66]
 [0.66 0.00 -0.75]
 [0.00 1.00 0.00]]
u*s = 
[[-0.75 0.66 0.00]
 [-2.07 -0.84 0.00]
 [-2.16 0.57 0.00]]
s*vh = 
[[-2.31 0.00 -2.04]
 [0.80 0.00 -0.91]
 [0.00 0.00 0.00]]
